name: EB deploy prod
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      - name: Init EB CLI
        run: |
          printf '\n\n\n\n' | eb init ${{ secrets.AWS_EB_APPLICATION_NAME }} --region ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Select EB Environment
        run: |
          eb use ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
